<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Arr;

#[Signature('translations:types')]
#[Description('Write the TypeScript union of every translation key')]
class GenerateTranslationTypes extends Command
{
    /**
     * Turn lang/nl into a type the frontend can be wrong against.
     *
     * Generated rather than hand-kept, for the same reason Wayfinder generates
     * its routes: a list maintained by hand drifts the first week, and a key
     * that has drifted shows up as the key itself on screen — visible, but only
     * to whoever happens to open that page.
     *
     * Dutch is the source because that is the language this application is
     * written in; the English file is checked against it by a test rather than
     * by this command, which would otherwise report a missing translation as a
     * missing key.
     */
    public function handle(): int
    {
        $keys = [];

        foreach (glob(lang_path('nl/*.php')) ?: [] as $file) {
            $group = basename($file, '.php');

            foreach (array_keys(Arr::dot(require $file)) as $key) {
                $keys[] = "{$group}.{$key}";
            }
        }

        sort($keys);

        $union = implode("\n", array_map(
            fn (string $key): string => "    | '{$key}'",
            $keys,
        ));

        $path = resource_path('js/types/translations.d.ts');

        file_put_contents($path, <<<TS
        /*
         * Generated by `php artisan translations:types` from lang/nl.
         *
         * Do not edit: add the line to lang/nl and lang/en and run the command.
         */

        export type TranslationKey =
        {$union};

        TS);

        $this->info(count($keys).' sleutels weggeschreven naar '.basename($path).'.');

        return self::SUCCESS;
    }
}
